version: '3'

services:
  postgres:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      - POSTGRES_PASSWORD=123456
      # POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgAdmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456 

# volumes:
#   postgres-db:
#     external: true
